DROP TABLE IF EXISTS informaciongeoportal;

-- Converted by db_converter
-- START TRANSACTION;
-- SET standard_conforming_strings=off;
-- SET escape_string_warning=off;
-- SET CONSTRAINTS ALL DEFERRED;

CREATE TABLE informaciongeoportal (
    "paisoriginal" varchar(100) DEFAULT NULL,
    "estadooriginal" varchar(100) DEFAULT NULL,
    "municipiooriginal" varchar(100) DEFAULT NULL,
    "regionmarinamapa" varchar(100) DEFAULT NULL,
    "geoportal" varchar(100) DEFAULT NULL,
    "grupobio" varchar(300) DEFAULT NULL,
    "subgrupobio" varchar(400) DEFAULT NULL,
    "familiavalida" varchar(300) DEFAULT NULL,
    "generovalido" varchar(300) DEFAULT NULL,
    "especievalida" varchar(200) DEFAULT NULL,
    "nom059" varchar(300) DEFAULT NULL,
    "cites" text ,
    "iucn" text ,
    "prioritaria" varchar(200) DEFAULT NULL,
    "exoticainvasora" varchar(40) DEFAULT NULL,
    "longitud" double precision DEFAULT NULL,
    "latitud" double precision DEFAULT NULL,
    "estadomapa" varchar(300) DEFAULT NULL,
    "municipiomapa" varchar(160) DEFAULT NULL,
    "localidad" varchar(1024) DEFAULT NULL,
    "fechacolecta" varchar(20) DEFAULT NULL,
    "anp" varchar(500) DEFAULT NULL,
    "probablelocnodecampo" varchar(4) DEFAULT NULL,
    "categoriaresidenciaaves" varchar(200) DEFAULT NULL,
    "formadecrecimiento" varchar(200) DEFAULT NULL,
    "fuente" varchar(300) DEFAULT NULL,
    "taxonextinto" varchar(30) DEFAULT NULL,
    "usvserieVI" varchar(200) DEFAULT NULL,
    "urlejemplar" varchar(200) DEFAULT NULL,
    "idejemplar" varchar(100) NOT NULL DEFAULT '',
    "ultimafechaactualizacion" date DEFAULT NULL,
    "idnombrecatvalido" varchar(40) DEFAULT NULL,
    "idnombrecat" varchar(40) DEFAULT NULL,
    "reino" varchar(300) DEFAULT NULL,
    "phylumdivision" varchar(300) DEFAULT NULL,
    "clase" varchar(300) DEFAULT NULL,
    "orden" varchar(300) DEFAULT NULL,
    "familia" varchar(300) DEFAULT NULL,
    "genero" varchar(300) DEFAULT NULL,
    "especie" varchar(200) DEFAULT NULL,
    "calificadordeterminacion" varchar(200) DEFAULT NULL,
    "categoriainfraespecie" varchar(40) DEFAULT NULL,
    "categoriainfraespecie2" varchar(40) DEFAULT NULL,
    "autor" varchar(400) DEFAULT NULL,
    "estatustax" varchar(40) DEFAULT NULL,
    "reftax" varchar(1024) DEFAULT NULL,
    "taxonvalidado" varchar(4) DEFAULT NULL,
    "reinovalido" varchar(300) DEFAULT NULL,
    "phylumdivisionvalido" varchar(300) DEFAULT NULL,
    "clasevalida" varchar(300) DEFAULT NULL,
    "ordenvalido" varchar(300) DEFAULT NULL,
    "categoriainfraespecievalida" varchar(40) DEFAULT NULL,
    "categoriainfraespecie2valida" varchar(40) DEFAULT NULL,
    "autorvalido" varchar(400) DEFAULT NULL,
    "reftaxvalido" varchar(1024) DEFAULT NULL,
    "nombrecomun" text ,
    "ambiente" text,
    "validacionambiente" varchar(150),
    "endemismo" varchar(30) DEFAULT NULL,
    "nivelprioridad" varchar(40) DEFAULT NULL,
    "region" varchar(300) DEFAULT NULL,
    "datum" varchar(300) DEFAULT NULL,
    "geovalidacion" varchar(140) DEFAULT NULL,
    "paismapa" varchar(300) DEFAULT NULL,
    "claveestadomapa" varchar(20) DEFAULT NULL,
    "mt24claveestadomapa" varchar(20) DEFAULT NULL,
    "mt24nombreestadomapa" varchar(300) DEFAULT NULL,
    "clavemunicipiomapa" varchar(20) DEFAULT NULL,
    "mt24clavemunicipiomapa" varchar(20) DEFAULT NULL,
    "mt24nombremunicipiomapa" varchar(160) DEFAULT NULL,
    "incertidumbreXY" integer DEFAULT NULL,
    "altitudmapa" int2 DEFAULT NULL,
    "usvserieI" varchar(200) DEFAULT NULL,
    "usvserieII" varchar(200) DEFAULT NULL,
    "usvserieIII" varchar(200) DEFAULT NULL,
    "usvserieIV" varchar(200) DEFAULT NULL,
    "usvserieV" varchar(200) DEFAULT NULL,
    "coleccion" varchar(300) DEFAULT NULL,
    "institucion" varchar(1024) DEFAULT NULL,
    "paiscoleccion" varchar(300) DEFAULT NULL,
    "numcatalogo" varchar(200) DEFAULT NULL,
    "numcolecta" varchar(200) DEFAULT NULL,
    "procedenciaejemplar" varchar(40) DEFAULT NULL,
    "determinador" varchar(1024) DEFAULT NULL,
    "fechadeterminacion" varchar(20) DEFAULT NULL,
    "diadeterminacion" int4 DEFAULT NULL,
    "mesdeterminacion" int4 DEFAULT NULL,
    "aniodeterminacion" int2 DEFAULT NULL,
    "colector" varchar(1024) DEFAULT NULL,
    "diacolecta" int4 NULL DEFAULT 99,
    "mescolecta" int4 NULL DEFAULT 99,
    "aniocolecta" int4 NULL DEFAULT 9999,
    "tipo" varchar(300) DEFAULT NULL,
    "ejemplarfosil" varchar(30) DEFAULT NULL,
    "proyecto" varchar(300) NOT NULL DEFAULT '',
    "formadecitar" text ,
    "licenciauso" varchar(255),
    "urlproyecto" varchar(1024) DEFAULT NULL,
    "urlorigen" varchar(255),
    "obsusoinfo" varchar(1024) DEFAULT NULL,
    "version" varchar(20) DEFAULT NULL,
    "idestadomapa" int4  DEFAULT NULL,
    "idmunicipiomapa" int2  DEFAULT NULL,
    "mt24idestadomapa" int4  DEFAULT NULL,
    "mt24idmunicipiomapa" int2  DEFAULT NULL,
    "idanpfederal1" integer  DEFAULT NULL,
    "idanpfederal2" integer  DEFAULT NULL,
    "especievalidabusqueda" varchar(200) DEFAULT NULL,
    "comentarioscat" varchar(1024) DEFAULT NULL,
    "comentarioscatvalido" varchar(1024) DEFAULT NULL,
    "homonimosgenero" text ,
    "homonimosespecie" text ,
    "homonimosinfraespecie" text ,
    "homonimosgenerocatvalido" text ,
    "homonimosespeciecatvalido" text ,
    "homonimosinfraespeciecatvalido" text ,
    "categoriataxonomica" varchar(300) DEFAULT NULL,
    PRIMARY KEY ("idejemplar")
);


-- -- Post-data save --
-- COMMIT;
-- START TRANSACTION;


-- -- Sequences --

-- -- Full Text keys --

-- COMMIT;
