CREATE TABLE IF NOT EXISTS informaciongeoportal (
    "paisoriginal" varchar(100) DEFAULT NULL,
    "estadooriginal" varchar(100) DEFAULT NULL,
    "municipiooriginal" varchar(100) DEFAULT NULL,
    "regionmarinamapa" varchar(100) DEFAULT NULL,
    "geoportal" varchar(100) DEFAULT NULL,
    "grupobio" text,
    "subgrupobio" varchar(400) DEFAULT NULL,
    "familiavalida" text,
    "generovalido" text,
    "especievalida" varchar(200) DEFAULT NULL,
    "nom059" text,
    "cites" text ,
    "iucn" text ,
    "prioritaria" varchar(200) DEFAULT NULL,
    "exoticainvasora" varchar(40) DEFAULT NULL,
    "longitud" double precision DEFAULT NULL,
    "latitud" double precision DEFAULT NULL,
    "estadomapa" text,
    "municipiomapa" varchar(160) DEFAULT NULL,
    "localidad" text,
    "fechacolecta" varchar(20) DEFAULT NULL,
    "anp" varchar(500) DEFAULT NULL,
    "probablelocnodecampo" varchar(4) DEFAULT NULL,
    "categoriaresidenciaaves" varchar(200) DEFAULT NULL,
    "formadecrecimiento" varchar(200) DEFAULT NULL,
    "fuente" text,
    "taxonextinto" varchar(30) DEFAULT NULL,
    "usvserieVI" varchar(200) DEFAULT NULL,
    "urlejemplar" varchar(200) DEFAULT NULL,
    "idejemplar" varchar(100) NOT NULL DEFAULT '',
    "ultimafechaactualizacion" date DEFAULT NULL,
    "idnombrecatvalido" varchar(40) DEFAULT NULL,
    "idnombrecat" varchar(40) DEFAULT NULL,
    "reino" text,
    "phylumdivision" text,
    "clase" text,
    "orden" text,
    "familia" text,
    "genero" text,
    "especie" varchar(200) DEFAULT NULL,
    "calificadordeterminacion" varchar(200) DEFAULT NULL,
    "categoriainfraespecie" varchar(40) DEFAULT NULL,
    "categoriainfraespecie2" varchar(40) DEFAULT NULL,
    "autor" varchar(400) DEFAULT NULL,
    "estatustax" varchar(40) DEFAULT NULL,
    "reftax" text,
    "taxonvalidado" varchar(4) DEFAULT NULL,
    "reinovalido" text,
    "phylumdivisionvalido" text,
    "clasevalida" text,
    "ordenvalido" text,
    "categoriainfraespecievalida" varchar(40) DEFAULT NULL,
    "categoriainfraespecie2valida" varchar(40) DEFAULT NULL,
    "autorvalido" varchar(400) DEFAULT NULL,
    "reftaxvalido" text,
    "nombrecomun" text ,
    "ambiente" text,
    "validacionambiente" varchar(150),
    "endemismo" varchar(30) DEFAULT NULL,
    "nivelprioridad" varchar(40) DEFAULT NULL,
    "region" text,
    "datum" text,
    "geovalidacion" varchar(140) DEFAULT NULL,
    "paismapa" text,
    "claveestadomapa" varchar(20) DEFAULT NULL,
    "mt24claveestadomapa" varchar(20) DEFAULT NULL,
    "mt24nombreestadomapa" text,
    "clavemunicipiomapa" varchar(20) DEFAULT NULL,
    "mt24clavemunicipiomapa" varchar(20) DEFAULT NULL,
    "mt24nombremunicipiomapa" varchar(160) DEFAULT NULL,
    "incertidumbreXY" integer DEFAULT NULL,
    "altitudmapa" int2 DEFAULT NULL,
    "usvserieI" varchar(200) DEFAULT NULL,
    "usvserieII" varchar(200) DEFAULT NULL,
    "usvserieIII" varchar(200) DEFAULT NULL,
    "usvserieIV" varchar(200) DEFAULT NULL,
    "usvserieV" varchar(200) DEFAULT NULL,
    "coleccion" text,
    "institucion" text,
    "paiscoleccion" text,
    "numcatalogo" varchar(200) DEFAULT NULL,
    "numcolecta" varchar(200) DEFAULT NULL,
    "procedenciaejemplar" varchar(40) DEFAULT NULL,
    "determinador" text,
    "fechadeterminacion" varchar(20) DEFAULT NULL,
    "diadeterminacion" int4 DEFAULT NULL,
    "mesdeterminacion" int4 DEFAULT NULL,
    "aniodeterminacion" int2 DEFAULT NULL,
    "colector" text,
    "diacolecta" int4 NULL DEFAULT 99,
    "mescolecta" int4 NULL DEFAULT 99,
    "aniocolecta" int4 NULL DEFAULT 9999,
    "tipo" text,
    "ejemplarfosil" varchar(30) DEFAULT NULL,
    "proyecto" text NOT NULL DEFAULT '',
    "formadecitar" text ,
    "licenciauso" varchar(255),
    "urlproyecto" text,
    "urlorigen" varchar(255),
    "obsusoinfo" text,
    "version" varchar(20) DEFAULT NULL,
    "idestadomapa" int4  DEFAULT NULL,
    "idmunicipiomapa" int2  DEFAULT NULL,
    "mt24idestadomapa" int4  DEFAULT NULL,
    "mt24idmunicipiomapa" int2  DEFAULT NULL,
    "idanpfederal1" integer  DEFAULT NULL,
    "idanpfederal2" integer  DEFAULT NULL,
    "especievalidabusqueda" varchar(200) DEFAULT NULL,
    "comentarioscat" text,
    "comentarioscatvalido" text,
    "homonimosgenero" text ,
    "homonimosespecie" text ,
    "homonimosinfraespecie" text ,
    "homonimosgenerocatvalido" text ,
    "homonimosespeciecatvalido" text ,
    "homonimosinfraespeciecatvalido" text ,
    "categoriataxonomica" text,
    PRIMARY KEY ("idejemplar")
);


-- -- Post-data save --
-- COMMIT;
-- START TRANSACTION;


-- -- Sequences --

-- -- Full Text keys --

-- COMMIT;
